project:
  type: website
  output-dir: docs

website:
  title: "Xiangmin Sun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    light: cerulean
    dark: slate
    css: styles.css
    toc: true

editor: visual

